GET http://localhost/user/all
###

GET http://localhost/user/chenzhongzhi
###

POST http://localhost/user
Content-Type: application/json

{
"userName":"mapl",
"userPassword":"Password00001",
"userEmail":"ops@ops.ops"
}