server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      connection-init-sql: select 1 from dual
      data-source-class-name: com.mysql.jdbc.Driver
      maximum-pool-size: 10

mybatis:
  mapper-locations: classpath:mapper/*
  type-aliases-package: com.maple.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
